# Copyright (c) 2014-2016 Software Architecture Group (Hasso Plattner Institute)

language: smalltalk
sudo: false

os: osx

smalltalk:
  - Squeak-trunk
  - Squeak-5.0
  - Squeak-4.6

baseline: Animations

env:
  global:
    - PACKAGES="/repository"
